//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BigDaddy.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BigDaddy.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base.
        /// </summary>
        public static string BaseTab {
            get {
                return ResourceManager.GetString("BaseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Edit.
        /// </summary>
        public static string EditMenu {
            get {
                return ResourceManager.GetString("EditMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Column(s).
        /// </summary>
        public static string EditMenu_AddColumns {
            get {
                return ResourceManager.GetString("EditMenu_AddColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Column(s).
        /// </summary>
        public static string EditMenu_CopyColumns {
            get {
                return ResourceManager.GetString("EditMenu_CopyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Column(s).
        /// </summary>
        public static string EditMenu_CutColumns {
            get {
                return ResourceManager.GetString("EditMenu_CutColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Column(s).
        /// </summary>
        public static string EditMenu_DuplicateColumns {
            get {
                return ResourceManager.GetString("EditMenu_DuplicateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Column(s).
        /// </summary>
        public static string EditMenu_PasteColumns {
            get {
                return ResourceManager.GetString("EditMenu_PasteColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Column(s).
        /// </summary>
        public static string EditMenu_RemoveColumns {
            get {
                return ResourceManager.GetString("EditMenu_RemoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditTab {
            get {
                return ResourceManager.GetString("EditTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Out of Memory.
        /// </summary>
        public static string Error_NotEnoughMemoryToLoadAllLinesCaption {
            get {
                return ResourceManager.GetString("Error_NotEnoughMemoryToLoadAllLinesCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was not enough memory to load all lines. The table is empty now!.
        /// </summary>
        public static string Error_NotEnoughMemoryToLoadAllLinesText {
            get {
                return ResourceManager.GetString("Error_NotEnoughMemoryToLoadAllLinesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _File.
        /// </summary>
        public static string FileMenu {
            get {
                return ResourceManager.GetString("FileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string FileMenu_Exit {
            get {
                return ResourceManager.GetString("FileMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New.
        /// </summary>
        public static string FileMenu_New {
            get {
                return ResourceManager.GetString("FileMenu_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open.
        /// </summary>
        public static string FileMenu_Open {
            get {
                return ResourceManager.GetString("FileMenu_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Save.
        /// </summary>
        public static string FileMenu_Save {
            get {
                return ResourceManager.GetString("FileMenu_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save_As.
        /// </summary>
        public static string FileMenu_SaveAs {
            get {
                return ResourceManager.GetString("FileMenu_SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        public static string MainDataGrid_CellContextMenu_Copy {
            get {
                return ResourceManager.GetString("MainDataGrid_CellContextMenu_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        public static string MainDataGrid_CellContextMenu_Cut {
            get {
                return ResourceManager.GetString("MainDataGrid_CellContextMenu_Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        public static string MainDataGrid_CellContextMenu_Paste {
            get {
                return ResourceManager.GetString("MainDataGrid_CellContextMenu_Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Column(s).
        /// </summary>
        public static string MainDataGrid_ColumnContextMenu_AddColumns {
            get {
                return ResourceManager.GetString("MainDataGrid_ColumnContextMenu_AddColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Column(s).
        /// </summary>
        public static string MainDataGrid_ColumnContextMenu_CopyColumns {
            get {
                return ResourceManager.GetString("MainDataGrid_ColumnContextMenu_CopyColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Column(s).
        /// </summary>
        public static string MainDataGrid_ColumnContextMenu_CutColumns {
            get {
                return ResourceManager.GetString("MainDataGrid_ColumnContextMenu_CutColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Column(s).
        /// </summary>
        public static string MainDataGrid_ColumnContextMenu_DuplicateColumns {
            get {
                return ResourceManager.GetString("MainDataGrid_ColumnContextMenu_DuplicateColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Column(s).
        /// </summary>
        public static string MainDataGrid_ColumnContextMenu_PasteColumns {
            get {
                return ResourceManager.GetString("MainDataGrid_ColumnContextMenu_PasteColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Column(s).
        /// </summary>
        public static string MainDataGrid_ColumnContextMenu_RemoveColumns {
            get {
                return ResourceManager.GetString("MainDataGrid_ColumnContextMenu_RemoveColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Load More....
        /// </summary>
        public static string MainDataGrid_LoadMore {
            get {
                return ResourceManager.GetString("MainDataGrid_LoadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_AddRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_AddRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_CopyRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_CopyRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_CutRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_CutRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_DuplicateRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_DuplicateRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste After Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_PasteAfterRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_PasteAfterRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste Before Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_PasteBeforeRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_PasteBeforeRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Row(s).
        /// </summary>
        public static string MainDataGrid_RowContextMenu_RemoveRows {
            get {
                return ResourceManager.GetString("MainDataGrid_RowContextMenu_RemoveRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines:.
        /// </summary>
        public static string MainStatusBar_Lines {
            get {
                return ResourceManager.GetString("MainStatusBar_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished.
        /// </summary>
        public static string MainStatusBar_LoadingStatus__Finished {
            get {
                return ResourceManager.GetString("MainStatusBar_LoadingStatus__Finished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string MainStatusBar_LoadingStatus__Loading {
            get {
                return ResourceManager.GetString("MainStatusBar_LoadingStatus__Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string MainStatusBar_LoadingStatus__Ready {
            get {
                return ResourceManager.GetString("MainStatusBar_LoadingStatus__Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenExpander {
            get {
                return ResourceManager.GetString("OpenExpander", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string OpenExpander_Cancel {
            get {
                return ResourceManager.GetString("OpenExpander_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Determine Total Number of Lines.
        /// </summary>
        public static string OpenExpander_DetermineTotalNumberOfLines {
            get {
                return ResourceManager.GetString("OpenExpander_DetermineTotalNumberOfLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import.
        /// </summary>
        public static string OpenExpander_Import {
            get {
                return ResourceManager.GetString("OpenExpander_Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower Bound.
        /// </summary>
        public static string OpenExpander_LowerBound {
            get {
                return ResourceManager.GetString("OpenExpander_LowerBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reimport.
        /// </summary>
        public static string OpenExpander_Reimport {
            get {
                return ResourceManager.GetString("OpenExpander_Reimport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator.
        /// </summary>
        public static string OpenExpander_Separator {
            get {
                return ResourceManager.GetString("OpenExpander_Separator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper Bound.
        /// </summary>
        public static string OpenExpander_UpperBound {
            get {
                return ResourceManager.GetString("OpenExpander_UpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are errors to correct..
        /// </summary>
        public static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is lower the minimum.
        /// </summary>
        public static string ValidationError_ValueLowerMinimum {
            get {
                return ResourceManager.GetString("ValidationError_ValueLowerMinimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The value is not numerical..
        /// </summary>
        public static string ValidationError_ValueNotNumerical {
            get {
                return ResourceManager.GetString("ValidationError_ValueNotNumerical", resourceCulture);
            }
        }
    }
}
